In [1]:
import numpy as np
a = np.random.random((10,3))
print (a)
b = abs(a - 0.5)
res = a[np.arange(10), np.argmin(b, axis = 1)]
print (res)

[[0.69824642 0.41794864 0.46627098]
 [0.89870127 0.50826207 0.8965691 ]
 [0.35949781 0.94800181 0.37830107]
 [0.04574375 0.95820389 0.76459079]
 [0.52573237 0.88421974 0.53374465]
 [0.43275742 0.8700188  0.95858794]
 [0.76473389 0.6143473  0.84548757]
 [0.55036506 0.01705212 0.90687993]
 [0.397402   0.89062222 0.95527987]
 [0.03432103 0.43574676 0.08108845]]
[0.46627098 0.50826207 0.37830107 0.76459079 0.52573237 0.43275742
 0.6143473  0.55036506 0.397402   0.43574676]


In [2]:
import numpy as np
a = np.random.random((6,6))
print (a)
b = np.sum(a, axis = 1)
c = np.argmin(a, axis = 0)
print (b/a[c, np.arange(6)])

[[0.60255916 0.73716508 0.64316462 0.91380075 0.20760798 0.58559558]
 [0.69711753 0.19152809 0.01991084 0.06239057 0.07747178 0.19120804]
 [0.63154721 0.03711934 0.47759256 0.66798723 0.21612776 0.89070145]
 [0.31292876 0.33465117 0.3481523  0.7159023  0.58383688 0.8983947 ]
 [0.42697818 0.38165937 0.66853422 0.11010017 0.40498058 0.84656224]
 [0.2611176  0.44530059 0.71393629 0.35323981 0.18681729 0.74541666]]
[ 14.13115489  33.39571523 146.70782992  51.19149034  36.64321148
  14.15122662]


In [3]:
import numpy as np
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
zero = x==0
print (x[1:][zero[:-1]].max())

5


In [5]:
import numpy as np
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
np.add.at (x, i, 1)
print(x)

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


In [26]:
import numpy as np
a = np.arange(16).reshape(4, 4)
N=a.shape[0]
print (a)
for i in range (2*N-1):
    print ( {i : [a[j][i-j] for j in range(i+1) if j < N and i-j < N]})

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
{0: [0]}
{1: [1, 4]}
{2: [2, 5, 8]}
{3: [3, 6, 9, 12]}
{4: [7, 10, 13]}
{5: [11, 14]}
{6: [15]}
