In [14]:
import numpy as np
a = np.random.random((10,3))
print (a)
b = abs(a - 0.5)
res = np.argmin(b, axis = 1)
for i in range (10):
    print (a[i][res[i]])


[[0.82428326 0.59710729 0.87119092]
 [0.49276876 0.0867404  0.98026072]
 [0.35644133 0.82870191 0.44579407]
 [0.86399754 0.85069485 0.52367992]
 [0.48864885 0.34597502 0.63038402]
 [0.56016952 0.81439027 0.24584113]
 [0.73086141 0.82497621 0.56407044]
 [0.72233977 0.41272243 0.30344041]
 [0.34985541 0.06924023 0.20748292]
 [0.41281896 0.20817494 0.73946629]]
0.597107287540529
0.49276876362025557
0.4457940694973688
0.5236799223152843
0.4886488549167062
0.560169522516609
0.5640704432830045
0.4127224314857373
0.3498554083733505
0.41281895657619794


In [69]:
import numpy as np
a = np.random.random((6,6))
print (a)
b = np.sum(a, axis = 1)
print(b)
c = np.argmin(a, axis = 0)
print (c)
for i in range(6):
    print (b[i]/a[c[i]][i])

[[0.75096694 0.35421158 0.51306286 0.90116673 0.3249271  0.39895388]
 [0.17948848 0.35747194 0.57637195 0.6054505  0.71091637 0.93287302]
 [0.99944291 0.92510002 0.1414238  0.93408953 0.21697735 0.47319434]
 [0.04805163 0.77372404 0.4303373  0.22030671 0.89515737 0.82038665]
 [0.1069818  0.74379501 0.98398178 0.54638116 0.54123382 0.25482221]
 [0.2885168  0.28197739 0.83023753 0.23082331 0.1313554  0.12847022]]
[3.24328908 3.36257225 3.69022796 3.18796371 3.17719577 1.89138065]
[3 5 2 3 5 5]
67.49591965253188
11.924971130491013
26.093400627319827
14.470569842313964
24.187781161589825
14.722327811861863


In [73]:
import numpy as np
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
zero = x==0
print (x[1:][zero[:-1]].max())

5


In [79]:
import numpy as np
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
for j in range(10):
    mask = i - j == 0
    print (x[j]+len(i[mask]))


2.0
2.0
2.0
2.0
1.0
4.0
1.0
1.0
2.0
1.0


In [23]:
import numpy as np
a = np.arange(16).reshape(4, 4)
print (a)
key = np.array
for i in range (4):
    key.append = i
    for j in range(i+1):
        value = [a[i][i-j]]
print (key)
print(value)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


AttributeError: 'builtin_function_or_method' object has no attribute 'append'